{% set name = "chamber" %}
{% set version = "2.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/segmentio/chamber/releases/download/v{{ version }}/chamber-v{{ version }}-darwin-amd64 # [osx]
  sha256: 9b2a937f4221890563855709ef3b989922930d6e2b1097dd13f2bcfc6903e1ac # [osx]
  url: https://github.com/segmentio/chamber/releases/download/v{{ version }}/chamber-v{{ version }}-linux-amd64 # [linux64]
  sha256: d7991809838c38c3434b8ff853074086cae0cb0d49f2012bf293e7c0b229702a # [linux64]

build:
  string: '0'

test:
  commands:
    - chamber version

about:
  home: https://github.com/segmentio/chamber
  license: MIT
  summary: CLI for managing secrets
