{% set name = "chamber" %}
{% set version = "2.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/segmentio/chamber/releases/download/v{{ version }}/chamber-v{{ version }}-darwin-amd64 # [osx]
  sha256: cfe1eeee927aa3ada550ba978640afbaaa91475ef8106dafb6285b8474de28eb # [osx]
  url: https://github.com/segmentio/chamber/releases/download/v{{ version }}/chamber-v{{ version }}-linux-amd64 # [linux64]
  sha256: 4a47bd9f7fb46ba4a3871efbb60931592defe7c954bd10b4e92323aa30874fc1 # [linux64]

build:
  string: '0'

test:
  commands:
    - chamber version

about:
  home: https://github.com/segmentio/chamber
  license: MIT
  summary: CLI for managing secrets
