{% set name = "gitleaks" %}
{% set version = "8.7.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/zricethezav/gitleaks/releases/download/v{{ version }}/gitleaks_{{ version }}_darwin_x64.tar.gz # [osx]
  sha256: 73a51a817e3784b9a353cec8bce09270c35eab3c7cdc2dbe564e4a27786df1df # [osx]
  url: https://github.com/zricethezav/gitleaks/releases/download/v{{ version }}/gitleaks_{{ version }}_linux_x64.tar.gz # [linux64]
  sha256: 031dc0da028228fa1ffd501680e4e262669b02592101fda2a1b3d1d94f6cdf67 # [linux64]

build:
  string: '1'
  binary_relocation: False

test:
  commands:
    - gitleaks version

about:
  home: https://github.com/zricethezav/gitleaks
  license: MIT
  summary: Scan git repos (or files) for secrets using regex and entropy key
