package:
  name: gcc-arm-none-eabi
  version: 10.3.2021.10

source:
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-mac.tar.bz2 # [osx]
  sha256: fb613dacb25149f140f73fe9ff6c380bb43328e6bf813473986e9127e2bc283b # [osx]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 # [linux64]
  sha256: 97dbb4f019ad1650b732faffcc881689cedc14e2b7ee863d390e0a41ef16c9a3 # [linux64]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-win32.zip # [win]
  sha256: d287439b3090843f3f4e29c7c41f81d958a5323aecefcf705c203bfd8ae3f2e7 # [win]

build:
  string: '0'

test:
  commands:
    - arm-none-eabi-gcc --version

about:
  home: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm
  license: GPL
  summary: GNU Arm Embedded Toolchain
