CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk        # [osx]
python:
  - '3.6'
  - '3.8'
pin_run_as_build:
  expat:
    max_pin: x.x
  gmp:
    max_pin: x
  libiconv:
    max_pin: x.x
  mpfr:
    max_pin: x
  ncurses:
    max_pin: x.x
  xz:
    max_pin: x.x
  zlib:
    max_pin: x.x
expat:
  - 2.2
gmp:
  - 6
libiconv:
  - 1.15
mpfr:
  - 4
ncurses:
  - 6.1
xz:
  - 5.2
zlib:
  - 1.2
