{% set name = "cpputest" %}
{% set version = "3.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.tar.gz
  sha256: c81dccc5a1bfc7fc6511590c0a61def5f78e3fb19cb8e1f889d8d3395a476456

build:
  number: "0"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - libtool
test:
  commands:
    - test -f ${PREFIX}/lib/libCppUTest.a

about:
  home: http://cpputest.github.io/
  dev_url: https://github.com/cpputest/cpputest
  doc_url: http://cpputest.github.io/manual.html
  license: BSD-3-Clause
  license_file: COPYING
  summary: CppUTest is a C /C++ based unit xUnit test framework for unit testing and for test-driving your code.
