package:
  name: gcc-arm-none-eabi
  version: 9.2020.q2.update

source:
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-src.tar.bz2
  md5: 50729355f3fa20d4dc26ef41b85acf69
  # url: https://f002.backblazeb2.com/file/tyhoff-public/gcc-arm-none-eabi-9-2020-q2-update.zip
  # md5: 03740468088050abd05c754d384488d3

  patches: 
    - 0001-Allow-LDFLAGS_CONDA-to-adjust-GDB-LDFLAGS.patch # [not win]

build:
  string: '0'

requirements:
  build:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - make
    - bison # [linux]
  host:
    - python {{ python }}
    - ncurses {{ ncurses }}
    - libiconv {{ libiconv }}
  run:
    - python {{ python }}
    - ncurses {{ ncurses }}
    - libiconv {{ libiconv }}
  rpaths:
    - lib

test:
  commands:
    - arm-none-eabi-gcc --version

about:
  home: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm
  license: GPL
  summary: GNU Arm Embedded Toolchain
