on:
  workflow_dispatch:
    inputs:
      PACKAGE_DIR:
        description: "set package dir to build and archive your package"
        required: true

jobs:
  build:
    name: 🛠️ build on ${{ matrix.platform }}

    # use the setup-miniconda helper, see
    # https://github.com/marketplace/actions/setup-miniconda for details
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-20.04, macos-11, windows-2022]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          # miniconda-version: "4.11.0"
          mamba-version: "0.22.1"
          channels: conda-forge,defaults

      - name: Conda info
        run: conda info

      - name: Install conda-build
        run: |
          conda install conda-build=3.21.4

      - name: Build package
        run: |
          mkdir -p ${{ github.event.inputs.PACKAGE_DIR }}/output
          conda build -c conda-forge --output-folder ${{ github.event.inputs.PACKAGE_DIR }}/output ${{ github.event.inputs.PACKAGE_DIR }}

      # upload-artifact to save the output files
      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ${{ github.event.inputs.PACKAGE_DIR }}/output
